site_name: Hotpot User Manual
theme:
  name: material
  palette:
    primary: teal
    accent: slate
  font:
    text: Ubuntu Sans
    code: Ubuntu Sans Mono
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - toc.integrate
nav:
  - Home: index.md
  - Dashboard: dashboard.md
  - Bookings: bookings.md
  - Deduplication: deduplication.md
  - Referrals: referrals.md
